### ISSUE TITLE
UpdateControllerTest failed

### ISSUE THREAD

**Issue by svanmieghem** [VlaamseMilieumaatschappij/BE-GOOD---Graph-Tracing-Engine#7]
FAILURE! - in com.geosparc.gte.rest.UpdateControllerTest
java.lang.AssertionError: expected:<503 SERVICE_UNAVAILABLE> but was:<200 OK>
	at com.geosparc.gte.rest.UpdateControllerTest.testUpdate(UpdateControllerTest.java:102)

**Comment by NielsCharlier** [comment]
is this why tests are disabled on github? I would prefer to put them back on. The test seems to rely on concurrency / timing issues, so it works locally but not on github. I'm going to disable that.

**Comment by NielsCharlier** [comment]
fixed
